---
gem:
  exclude:   # The following are stdlib gems that are bundled with sorbet. We exclude them to avoid
    #   overwriting the bundled versions with tapioca's untyped shims.
    - base64
    - benchmark
    - bigdecimal
    - cgi
    - csv
    - date
    - drb
    - erb
    - fiddle
    - irb
    - json
    - logger
    - matrix
    - msgpack # not stdlib, but bundled with sorbet
    - mutex_m
    - net-ftp
    - net-http
    - net-imap
    - net-protocol
    - net-smtp
    - nkf
    - openssl
    - ostruct
    - pp
    - prettyprint
    - pstore
    - psych
    - racc
    - rdoc
    - reline
    - rexml
    - securerandom
    - set
    - stringio
    - time
    - timeout
    - tsort
    - uri
    - webrick
    - zlib
    # These gems are not referenced in the repo, so we don't bother with them
    - diff-lcs
    - docile
    - erubi
    - language_server-protocol
    - netrc
    - parallel
    - prettier_print
    - rainbow
    - rbi
    - redcarpet
    - rubocop-packaging
    - rubocop-performance
    - rubocop-rake
    - rubocop-sorbet
    - ruby-progressbar
    - simplecov-html
    - simplecov_json_formatter
    - spoom
    - strscan
    - syntax_tree
    - tapioca
    - thor
    - unicode-display_width
    - unicode-emoji
