---
gem:
  exclude:
    - diff-lcs
    - docile
    - erubi
    - irb
    - json
    - language_server-protocol
    - netrc
    - parallel
    - prettier_print
    - racc
    - rainbow
    - rbi
    - redcarpet
    - rexml
    - rubocop-packaging
    - rubocop-performance
    - rubocop-rake
    - rubocop-sorbet
    - ruby-progressbar
    - simplecov-html
    - simplecov_json_formatter
    - spoom
    - strscan
    - syntax_tree
    - tapioca
    - thor
    - unicode-display_width
    - unicode-emoji
